import artistsJson from "@/data/artists.json";
import artworksJson from "@/data/artworks.json";
import connectionsJson from "@/data/connections.json";
import movementsJson from "@/data/movements.json";
import summaryJson from "@/data/summary.json";

export { artworkAlt, displayTitle } from "@/lib/artwork-format";

export type Provenance = {
  /** Wikidata QID for the painting itself (e.g. "Q12418" for Mona Lisa).
   *  Null when the local Commons file isn't the canonical wdt:P18 image
   *  on any Wikidata item. */
  wikidataId: string | null;
  wikidataUrl: string | null;
  /** P195 — institution that owns the work. */
  collection: string | null;
  collectionWikidataId: string | null;
  /** P276 — current physical location (often the same as collection). */
  location: string | null;
  /** P217 — accession / inventory number. */
  inventory: string | null;
  /** P973 — canonical museum page for the work. */
  describedAt: string | null;
  /** Resolved [N] footnote URLs scraped from the Commons file page,
   *  capped at 4. Useful as a "see also" list when there's no Wikidata
   *  describedAt URL. */
  sourceLinks: { label: string; url: string }[];
};

export type Artwork = {
  id: string;
  title: string;
  /** Curator-supplied English title used in preference to `title` when the
   *  source title is romaji/native script or a non-Latin original (e.g.
   *  "Tabi miyage dai sanshū" → "Souvenirs of Travel III: Tazawako
   *  Gozanoishi"). Populated from `metadata/title-overrides.json` keyed
   *  by `<folder>/<filename>`. */
  englishTitle: string | null;
  artist: string | null;
  artistSlug: string;
  year: number | null;
  dateCreated: string | null;
  /** Raw non-Gregorian date string before `scripts/clean-japanese-dates.mjs`
   *  rewrote it (e.g. "大正15年出版" for the cleaned "1926"). Preserved for
   *  transparency on the artwork detail page; null when no conversion
   *  happened. Loaded from `metadata/date-originals.json`. */
  originalDateString: string | null;
  description: string | null;
  folder: string;
  objectKey: string;
  width: number | null;
  height: number | null;
  realDimensions: {
    widthCm: number;
    heightCm: number;
    source: "wikidata" | "wikimedia-template" | "wikimedia-template-mm" | "static";
  } | null;
  /** Widths (in px) for which a pre-built variant exists under
   *  assets-web/<folder>/<basename>/<width>.{avif,webp}. Emitted by
   *  `pnpm assets:build-data` at build time; consumers use it to avoid
   *  attempting fetches for variants that don't exist yet. `null` when
   *  nothing has been shrunk for this artwork. */
  variantWidths: number[] | null;
  fileUrl: string;
  commonsUrl: string;
  credit: string | null;
  license: string;
  movement: string | null;
  nationality: string | null;
  /** Real provenance from Wikidata + resolved Commons footnote URLs.
   *  Generated by `node scripts/fetch-provenance.mjs`; null when nothing
   *  was found. */
  provenance: Provenance | null;
};

export type Artist = {
  slug: string;
  name: string;
  born: number | null;
  died: number | null;
  nationality: string | null;
  movement: string | null;
  count: number;
  minYear: number | null;
  maxYear: number | null;
  coverFileUrl: string | null;
  coverObjectKey: string | null;
  coverTitle: string | null;
  /** variantWidths of the cover artwork — see Artwork.variantWidths. Null
   *  when the cover has no pre-built variants yet. */
  coverVariantWidths: number[] | null;
};

export type Connection = {
  source: string;
  target: string;
  label: string;
  kind: "known" | "movement";
};

export const artworks = artworksJson as Artwork[];
export const artists = artistsJson as Artist[];
export const movements = movementsJson as string[];
export const connections = connectionsJson as Connection[];

/** Slim projection of Artwork — the fields that listing pages, browsers,
 *  the timeline, the lightbox, and the 3D gallery actually read. The
 *  full Artwork (~3.4 MB / 1.15 KB per row across descriptions,
 *  provenance, credit, source URLs) was being serialised into the RSC
 *  payload on every home / timeline / gallery-3d visit because the
 *  client components took `Artwork[]`. Server pages should pass
 *  `artworkListings` to anything client; only the /artwork/[id] detail
 *  page (server component) still pulls the full record via
 *  getArtwork(). */
export type ArtworkListing = Pick<
  Artwork,
  | "id"
  | "title"
  | "englishTitle"
  | "artist"
  | "artistSlug"
  | "year"
  | "movement"
  | "nationality"
  | "objectKey"
  | "variantWidths"
  | "width"
  | "height"
  | "realDimensions"
>;

const _artworkListings: ArtworkListing[] = (artworksJson as Artwork[]).map((a) => ({
  id: a.id,
  title: a.title,
  englishTitle: a.englishTitle,
  artist: a.artist,
  artistSlug: a.artistSlug,
  year: a.year,
  movement: a.movement,
  nationality: a.nationality,
  objectKey: a.objectKey,
  variantWidths: a.variantWidths,
  width: a.width,
  height: a.height,
  realDimensions: a.realDimensions,
}));
export const artworkListings: ArtworkListing[] = _artworkListings;
export const summary = summaryJson as {
  totalArtworks: number;
  totalArtists: number;
  totalMovements: number;
  totalConnections: number;
  yearRange: { min: number | null; max: number | null };
};

export function getArtwork(id: string): Artwork | null {
  return artworks.find((a) => a.id === id) ?? null;
}

export function getArtist(slug: string): Artist | null {
  return artists.find((a) => a.slug === slug) ?? null;
}

export function getArtworksByArtist(slug: string): Artwork[] {
  return artworks.filter((a) => a.artistSlug === slug);
}

export function getConnectionsFor(slug: string): Connection[] {
  return connections.filter((c) => c.source === slug || c.target === slug);
}
