"use client";

import { Text } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import { Suspense, useCallback, useEffect, useRef, useState } from "react";
import * as THREE from "three";
import type { Artwork } from "@/lib/data";
import type { Placement } from "@/lib/gallery-layout/types";
import { variantUrl } from "@/lib/utils";
import { useNsfw } from "../nsfw-provider";
import { type PaintingEntry, registerPainting, unregisterPainting } from "./painting-registry";
import {
  FRAME_VARIANTS,
  type FrameVariantId,
  plaqueBaseMaterial,
  plaqueMountMaterial,
} from "./palette-materials";
import { getHiRes, loadHiRes, useCachedTexture } from "./texture-cache";

/**
 * One painting on a wall. Renders a thin box behind the canvas so the
 * painting has some depth (the wall behind is roughly 0.05 m away),
 * with a textured plane on the front. Registers itself with the
 * global painting-registry so the Player's aim raycast can skip the
 * full scene traversal.
 *
 * Prefer a 960 px variant — big enough to look crisp at 2 m wide, small
 * enough that a few hundred paintings on a floor fit in GPU memory
 * comfortably. The texture-cache handles LRU eviction + rAF-paced GPU
 * uploads so a floor-wide burst of loads doesn't hitch the frame.
 */
// Tiered proximity LOD. Each tier names a variant width and four
// distance bands:
//
//   prefetch ─ start the network fetch eagerly so the swap feels
//              instantaneous when the player crosses upgrade.
//   upgrade  ─ first time we display this tier (must be cached).
//   downgrade ─ hysteresis: keep displaying once selected until the
//              player retreats past this radius.
//   release  ─ abort any in-flight fetch past this distance.
//
// Tiers are listed highest → lowest. The base 960 px texture is
// always loaded by the parent <Painting>; the tiers below are
// upgrades on top of it.
//
// Bands are nested so each higher tier's window sits inside the next
// lower tier's. The 4096 px tier has the tightest, lowest-radius
// window — only used when the player is face-pressed against the
// canvas. A player walking a hallway at ~3 m/s crosses each band in
// ~150-300 ms — comfortably more than the LodController's 12-frame
// tick.
//
// Per-tier availability: each Artwork carries a `variantWidths` list
// of widths that were actually generated by `pnpm shrink` (a small
// source can't produce a 4096 px AVIF). At mount time we filter
// LOD_TIERS down to widths the artwork supports — paintings with
// small originals quietly stop at the largest available tier.
type LodTier = {
  width: number;
  prefetchSq: number;
  upgradeSq: number;
  downgradeSq: number;
  releaseSq: number;
};

const sq = (n: number) => n * n;

const LOD_TIERS: LodTier[] = [
  {
    width: 4096,
    prefetchSq: sq(1.4),
    upgradeSq: sq(0.55),
    downgradeSq: sq(0.85),
    releaseSq: sq(1.8),
  },
  {
    width: 2560,
    prefetchSq: sq(2.0),
    upgradeSq: sq(0.9),
    downgradeSq: sq(1.4),
    releaseSq: sq(3.0),
  },
  {
    width: 1920,
    prefetchSq: sq(4.0),
    upgradeSq: sq(1.8),
    downgradeSq: sq(2.8),
    releaseSq: sq(5.5),
  },
];

export function Painting({
  placement,
  onLoaded,
}: {
  placement: Placement;
  /** Fires once when the base 960 px texture has finished loading and
   *  the painting plane mounts. Used by Gallery3D to drive the
   *  "Loading first room…" progress bar on the start overlay. */
  onLoaded?: () => void;
}) {
  const { artwork, position, rotation, widthM, heightM, plaqueOnLeft } = placement;
  const url = variantUrl(artwork.objectKey, 960, "avif");
  const { mode } = useNsfw();
  // NSFW visibility for 3D paintings is binary: full texture, or
  // placeholder swatch. The placeholder takes the place of the
  // textured plane entirely so we never even fetch the high-res
  // variant for hidden/blurred items. The plaque + frame still
  // render so the gap doesn't look broken — visually similar to a
  // painting in conservation.
  const nsfwHidden = artwork.nsfw === true && mode !== "show";

  // Aspect-corrected plane size. The slot's widthM/heightM are derived
  // from realDimensions (or pixel aspect, or a default) — but those can
  // disagree with the texture's actual aspect, in which case the
  // texture would be stretched onto a mismatched plane and the painting
  // would visibly distort. Once the texture loads we re-fit the plane
  // to the texture's true aspect within the slot bounds. The frame and
  // plaque resize alongside it so the whole assembly stays aspect-true.
  const [renderDims, setRenderDims] = useState({ widthM, heightM });
  // Reset when the placement changes (room/floor swap).
  useEffect(() => {
    setRenderDims({ widthM, heightM });
  }, [widthM, heightM]);

  const handleTextureAspect = useCallback(
    (texAspect: number) => {
      if (!Number.isFinite(texAspect) || texAspect <= 0) return;
      const fitted = fitToAspect(texAspect, widthM, heightM);
      setRenderDims((prev) => {
        if (
          Math.abs(prev.widthM - fitted.widthM) < 0.001 &&
          Math.abs(prev.heightM - fitted.heightM) < 0.001
        ) {
          return prev;
        }
        return fitted;
      });
    },
    [widthM, heightM],
  );

  const variant = FRAME_VARIANTS[pickFrameVariant(artwork)];
  const frameDepth = variant.depth;
  const frameInset = variant.inset;

  // Liner is a flat rim sitting on top of the frame's front face,
  // sandwiched between the frame face (at z = frameDepth/2) and the
  // canvas plane (at z = 0.014). Keep ≥1.5 mm on both sides to stay well
  // out of depth-buffer noise. Liner is canvas-sized + 2 × width in XY
  // so it's strictly inside the frame outer rectangle (no XY clipping)
  // and the canvas plane occludes its centre, leaving a visible rim.
  const linerDepth = 0.001;
  const linerClearance = 0.0015;
  const linerZ = frameDepth / 2 + linerClearance + linerDepth / 2;

  const dW = renderDims.widthM;
  const dH = renderDims.heightM;

  return (
    <group position={position} rotation={rotation}>
      <mesh>
        <boxGeometry args={[dW + frameInset * 2, dH + frameInset * 2, frameDepth]} />
        <primitive object={variant.material} attach="material" />
      </mesh>
      {variant.liner && (
        <mesh position={[0, 0, linerZ]}>
          <boxGeometry
            args={[dW + variant.liner.width * 2, dH + variant.liner.width * 2, linerDepth]}
          />
          <primitive object={variant.liner.material} attach="material" />
        </mesh>
      )}
      {nsfwHidden ? (
        <NsfwPlaceholder
          widthM={dW}
          heightM={dH}
          artwork={artwork}
          mode={mode}
          onLoaded={onLoaded}
        />
      ) : (
        <Suspense fallback={<FallbackSwatch widthM={dW} heightM={dH} artwork={artwork} />}>
          <PaintingPlane
            url={url}
            widthM={dW}
            heightM={dH}
            artwork={artwork}
            onLoaded={onLoaded}
            onTextureAspect={handleTextureAspect}
          />
        </Suspense>
      )}
      <Plaque artwork={artwork} widthM={dW} plaqueOnLeft={plaqueOnLeft} />
    </group>
  );
}

/** Refit a plane size to match a texture aspect while staying inside
 *  the slot's max bounds. Width-first: if width-fit overshoots height,
 *  fall back to height-fit. The returned dimensions are <= the input
 *  bounds in both axes — never grows beyond the slot. */
function fitToAspect(
  texAspect: number,
  maxWidthM: number,
  maxHeightM: number,
): { widthM: number; heightM: number } {
  let w = maxWidthM;
  let h = maxWidthM / texAspect;
  if (h > maxHeightM) {
    h = maxHeightM;
    w = maxHeightM * texAspect;
  }
  return { widthM: w, heightM: h };
}

// Pick a frame variant that complements the painting's era. Each rule
// below is a substring match against the artwork's `movement` field —
// some entries in the dataset are slashed combos like "Realism /
// Impressionism", so the first match wins. Anything unmatched (and the
// non-trivial number of artworks with `movement: null`) falls through to
// a stable hash on the artwork id, which keeps a consistent look per
// painting across reloads while still spreading variety across the
// gallery.
function pickFrameVariant(artwork: Artwork): FrameVariantId {
  const m = artwork.movement;
  if (m) {
    if (m.includes("Ukiyo-e")) return "redLacquer";
    if (
      m.includes("Renaissance") ||
      m.includes("Baroque") ||
      m.includes("Mannerism") ||
      m.includes("Academicism") ||
      m.includes("Neoclassicism")
    )
      return "gilded";
    if (
      m.includes("Impressionism") ||
      m.includes("Pre-Raphaelite") ||
      m.includes("Art Nouveau") ||
      m.includes("Neo-Impressionism")
    )
      return "paleAsh";
    if (
      m.includes("Modernism") ||
      m.includes("Fauvism") ||
      m.includes("Post-Impressionism") ||
      m.includes("Symbolism") ||
      m.includes("Expressionism")
    )
      return "ebony";
    if (
      m.includes("Dutch Golden Age") ||
      m.includes("Realism") ||
      m.includes("Romanticism") ||
      m.includes("Tonalism") ||
      m.includes("Regionalism")
    )
      return "walnut";
  }
  // Stable hash → deterministic per id, distributed across all five.
  const order: FrameVariantId[] = ["walnut", "ebony", "paleAsh", "gilded", "redLacquer"];
  let h = 0;
  for (let i = 0; i < artwork.id.length; i++) h = (h * 31 + artwork.id.charCodeAt(i)) | 0;
  return order[Math.abs(h) % order.length];
}

// ── Plaque ────────────────────────────────────────────────────────────
// A small museum-style label to the right of each painting at canvas
// centre height. Two-layer construction: a brass mount plate fixed
// flush to the wall, with a slightly inset cream face card on top
// carrying title / artist / year / dimensions in three sized lines.

// Cream face WIDTH is constant — placement code (place-paintings.ts)
// caps painting widths against PLAQUE_FOOTPRINT, which is built from
// this width plus PLAQUE_GAP. Don't change W without re-running
// placement. HEIGHT is adaptive: long titles bump the plaque taller
// so the title block doesn't crash through the byline (e.g. Hokusai
// "Tenman Bridge at Settsu Province (Sesshū Tenmanbashi), from the
// series Remarkable Views of Bridges in Various Provinces (Shokoku
// meikyō kiran)" — 144 chars overflows the standard plaque).
const PLAQUE_FACE_W = 0.28;
const PLAQUE_FACE_H_BASE = 0.18;
const PLAQUE_FACE_DEPTH = 0.004;
// Brushed-steel mount sits a hair larger than the face, framing it
// like a polished metal rim. Bigger reveal here makes the shimmer
// from the mount more visible at typical viewing distances.
const PLAQUE_MOUNT_REVEAL = 0.014;
const PLAQUE_MOUNT_W = PLAQUE_FACE_W + PLAQUE_MOUNT_REVEAL * 2;
const PLAQUE_MOUNT_DEPTH = 0.008;
const PLAQUE_GAP = 0.06;
// `placement.position` is offset PAINTING_WALL_OFFSET (= 0.02 m) into
// the room from the wall plane, so localZ = -0.02 lands the plaque
// back exactly on the wall surface. Keep this in sync with
// PAINTING_WALL_OFFSET in src/lib/gallery-layout/place-paintings.ts.
const PAINTING_WALL_OFFSET = 0.02;
// Small clearance so the plaque mount's back doesn't sit coplanar with
// the wall — coplanar geometry z-fights from any camera and shows
// through DoubleSide walls as wedge-shaped artefacts. 5 mm is enough
// for far-room viewing without making the plaque look detached.
const PLAQUE_WALL_CLEAR = 0.005;

const PLAQUE_TITLE_FONT = 0.022;
const PLAQUE_TITLE_LH = 1.15;
const PLAQUE_BYLINE_FONT = 0.018;
const PLAQUE_BYLINE_LH = 1.2;
const PLAQUE_DIMS_FONT = 0.014;
const PLAQUE_DIMS_LH = 1.15;
const PLAQUE_TEXT_PAD = 0.012;
const PLAQUE_LINE_GAP = 0.006;
/** Initial chars/line guess for the title font + plaque width — only
 *  used for the first frame before troika reports its actual rendered
 *  bounds via onSync. The bold title font averages ≈ 0.6 × fontSize
 *  per glyph; with title font 0.022 m and useful width 0.258 m that
 *  lands near ≈ 19 chars/line for ASCII and fewer with caps/diacritics.
 *  Pick conservative so the initial render usually OVERshoots, then
 *  we shrink to the measured size — better than the reverse, which
 *  flashes overlapping text. */
const PLAQUE_TITLE_CHARS_PER_LINE = 18;
const PLAQUE_BYLINE_CHARS_PER_LINE = 24;

const PLAQUE_TEXT_MAX_WIDTH = PLAQUE_FACE_W - 0.022;

/** Pull the rendered block height (in world meters) from a troika
 *  TextMesh's textRenderInfo. blockBounds is `[minX, minY, maxX, maxY]`
 *  and includes the line-height padding, so it equals the height the
 *  layout actually consumed. Returns null if sync hasn't completed yet. */
function readTroikaBlockHeight(mesh: unknown): number | null {
  const info = (mesh as { textRenderInfo?: { blockBounds?: ArrayLike<number> } } | null)
    ?.textRenderInfo;
  const bb = info?.blockBounds;
  if (!bb || bb.length < 4) return null;
  return Math.abs(bb[3] - bb[1]);
}

function Plaque({
  artwork,
  widthM,
  plaqueOnLeft,
}: {
  artwork: Artwork;
  widthM: number;
  plaqueOnLeft: boolean;
}) {
  const title = formatTitle(artwork.title, artwork.artist ?? undefined);
  const byline = formatByline(artwork);
  const dims = artwork.realDimensions
    ? `${artwork.realDimensions.widthCm.toFixed(0)} × ${artwork.realDimensions.heightCm.toFixed(0)} cm`
    : "";

  // Pre-render estimates — used for the first paint before troika
  // syncs and reports actual block bounds. The estimates use a word-
  // aware wrap so a single oversized word doesn't get overcounted, and
  // a conservative chars/line so the plaque starts a touch tall (and
  // shrinks to fit), never short (which would overlap text).
  const estTitleLines = estimateWrappedLines(title, PLAQUE_TITLE_CHARS_PER_LINE);
  const estBylineLines = estimateWrappedLines(byline, PLAQUE_BYLINE_CHARS_PER_LINE);
  const estTitleH = estTitleLines * PLAQUE_TITLE_FONT * PLAQUE_TITLE_LH;
  const estBylineH = estBylineLines * PLAQUE_BYLINE_FONT * PLAQUE_BYLINE_LH;

  // Measured block heights from troika onSync. Initialised to null so
  // the first render uses the estimates above; on the next frame the
  // measured values take over.
  const [titleH, setTitleH] = useState<number | null>(null);
  const [bylineH, setBylineH] = useState<number | null>(null);

  const handleTitleSync = useCallback((mesh: unknown) => {
    const h = readTroikaBlockHeight(mesh);
    if (h === null) return;
    setTitleH((prev) => (prev !== null && Math.abs(prev - h) < 0.0001 ? prev : h));
  }, []);
  const handleBylineSync = useCallback((mesh: unknown) => {
    const h = readTroikaBlockHeight(mesh);
    if (h === null) return;
    setBylineH((prev) => (prev !== null && Math.abs(prev - h) < 0.0001 ? prev : h));
  }, []);

  const titleBlockH = titleH ?? estTitleH;
  const bylineBlockH = bylineH ?? estBylineH;
  const dimsBlockH = dims ? PLAQUE_DIMS_FONT * PLAQUE_DIMS_LH : 0;
  const dimsGap = dims ? PLAQUE_LINE_GAP : 0;
  const stackedH =
    PLAQUE_TEXT_PAD * 2 + titleBlockH + PLAQUE_LINE_GAP + bylineBlockH + dimsGap + dimsBlockH;
  const PLAQUE_FACE_H = Math.max(PLAQUE_FACE_H_BASE, stackedH);
  const PLAQUE_MOUNT_H = PLAQUE_FACE_H + PLAQUE_MOUNT_REVEAL * 2;

  // Default hang is to the painting's right (local +X). Flip to the
  // left at right-corner cells so the plaque doesn't crash through the
  // perpendicular wall there.
  const sideSign = plaqueOnLeft ? -1 : 1;
  const localX = sideSign * (widthM / 2 + PLAQUE_GAP + PLAQUE_MOUNT_W / 2);
  const localY = 0;
  // Mount sits a few mm off the wall so it doesn't z-fight with it; face
  // is parked just in front of the mount; text floats a hair above the
  // face for the same reason.
  const mountCenterZ = -PAINTING_WALL_OFFSET + PLAQUE_WALL_CLEAR + PLAQUE_MOUNT_DEPTH / 2;
  const faceCenterZ = mountCenterZ + PLAQUE_MOUNT_DEPTH / 2 + PLAQUE_FACE_DEPTH / 2;
  const textZ = faceCenterZ + PLAQUE_FACE_DEPTH / 2 + 0.001;

  // Top-aligned text stack — title hugs the top edge, byline sits one
  // gap below the title block, dims one gap below the byline. Anchor
  // top so positions describe each block's UPPER edge regardless of
  // line count.
  const topY = PLAQUE_FACE_H / 2 - PLAQUE_TEXT_PAD;
  const titleTopY = topY;
  const bylineTopY = titleTopY - titleBlockH - PLAQUE_LINE_GAP;
  const dimsTopY = bylineTopY - bylineBlockH - PLAQUE_LINE_GAP;

  return (
    <group position={[localX, localY, 0]}>
      {/* Brass mount plate */}
      <mesh position={[0, 0, mountCenterZ]}>
        <boxGeometry args={[PLAQUE_MOUNT_W, PLAQUE_MOUNT_H, PLAQUE_MOUNT_DEPTH]} />
        <primitive object={plaqueMountMaterial} attach="material" />
      </mesh>
      {/* Cream face card on top of the mount */}
      <mesh position={[0, 0, faceCenterZ]}>
        <boxGeometry args={[PLAQUE_FACE_W, PLAQUE_FACE_H, PLAQUE_FACE_DEPTH]} />
        <primitive object={plaqueBaseMaterial} attach="material" />
      </mesh>
      {/* Title — bold and largest. */}
      <Text
        position={[0, titleTopY, textZ]}
        fontSize={PLAQUE_TITLE_FONT}
        lineHeight={PLAQUE_TITLE_LH}
        color="#0d0a08"
        fontWeight={700}
        anchorX="center"
        anchorY="top"
        maxWidth={PLAQUE_TEXT_MAX_WIDTH}
        textAlign="center"
        onSync={handleTitleSync}
      >
        {title}
      </Text>
      {/* Artist · year */}
      <Text
        position={[0, bylineTopY, textZ]}
        fontSize={PLAQUE_BYLINE_FONT}
        lineHeight={PLAQUE_BYLINE_LH}
        color="#1c1410"
        anchorX="center"
        anchorY="top"
        maxWidth={PLAQUE_TEXT_MAX_WIDTH}
        textAlign="center"
        onSync={handleBylineSync}
      >
        {byline}
      </Text>
      {/* Dimensions — smaller, slightly lighter. Never wraps (X × Y cm
          fits comfortably) so we don't need to measure it. */}
      {dims && (
        <Text
          position={[0, dimsTopY, textZ]}
          fontSize={PLAQUE_DIMS_FONT}
          lineHeight={PLAQUE_DIMS_LH}
          color="#3a2c22"
          anchorX="center"
          anchorY="top"
          maxWidth={PLAQUE_TEXT_MAX_WIDTH}
          textAlign="center"
        >
          {dims}
        </Text>
      )}
    </group>
  );
}

/** Word-aware wrap line counter — walks the words and pushes to a new
 *  line whenever the next word would exceed `maxChars`. Better than
 *  `ceil(len/maxChars)` because text wraps at word boundaries; a
 *  single oversized word past the boundary forces a fresh line even
 *  if the running total is well under `maxChars`. */
function estimateWrappedLines(text: string, maxChars: number): number {
  const trimmed = text.trim();
  if (!trimmed) return 1;
  const words = trimmed.split(/\s+/);
  let lines = 1;
  let lineLen = 0;
  for (const word of words) {
    if (lineLen === 0) {
      lineLen = word.length;
    } else if (lineLen + 1 + word.length <= maxChars) {
      lineLen += 1 + word.length;
    } else {
      lines++;
      lineLen = word.length;
    }
  }
  return Math.max(1, lines);
}

/** Normalise an artwork title for plaque display. Strips a handful
 *  of common upstream-import patterns that bloat the title without
 *  adding information at gallery-viewing scale:
 *
 *   - Wikimedia label noise: `label QS:Len,"Foo"` → `Foo`.
 *   - Stray `" Alternative title:` Wikidata segments — keep just the
 *     first quoted variant.
 *   - "from the series ..." Hokusai-style suffixes plus their
 *     parenthetical Japanese transliterations: the series name is
 *     redundant in a gallery setting and pushes single titles past
 *     150 chars.
 *   - Dataset breadcrumbs: " - Google Art Project", " - Google
 *     Cultural Institute", trailing ".jpg" filename remnants.
 *   - Audubon plate-list titles ("434 I. Little Tyrant Fly-catcher
 *     - 2. Small-headed Fly-catcher - …") collapsed to "Plate 434:
 *     Little Tyrant Fly-catcher (and N more)". */
/** Specific titles that aren't fixed by any pattern rule — typos,
 *  museum-tagged suffixes, "by Artist (year, museum)" trailers
 *  baked into the title field. Keys are NFC-normalised so they match
 *  regardless of whether the source data stores e.g. "Sesshū" as a
 *  precomposed glyph or "u + combining macron". */
const TITLE_REWRITES = new Map<string, string>(
  [
    [
      "Tenman Bridge at Settsu Province (Sesshū Tenmanbashi), from the series Remarkable Views of Bridges in Various Provinces (Shokoku meikyō kiran)",
      "Tenman Bridge at Settsu Province (Sesshū Tenmanbashi)",
    ],
    [
      "Wang Meng Dwelling in the Qingbian Mountains. ink on paper. 1366. 141x42",
      "Dwelling in the Qingbian Mountains",
    ],
    [
      "At first glance he looks very fiarce, but he s really a nice person",
      "At first glance he looks fierce, but he's really a nice person",
    ],
    [
      "Moreno Garden Bordighera 1884 - The Norton Museum Miami Florida",
      "Moreno Garden, Bordighera",
    ],
    [
      "Mt. Heng, after Juran (active ca. 960–965), from the Mustard Seed Garden Manual of Painting MET DP",
      "Mt. Heng, after Juran, from the Mustard Seed Garden Manual of Painting",
    ],
    [
      "Alexandra and Elena Pavlovna of Russia by E.Vigee-Lebrun (1796, Hermitage)",
      "Alexandra and Elena Pavlovna of Russia",
    ],
    [
      "An Experiment on a Bird in an Air Pump by Joseph Wright 'of Derby",
      "An Experiment on a Bird in an Air Pump",
    ],
    [
      "Famous Views of the 60 Provinces - #23. Yoro Waterfall in Mino Province",
      "Yoro Waterfall in Mino Province",
    ],
    [
      "36 Views of Mt. Fuji - #11. Wild Goose Hill and the Tone River",
      "Wild Goose Hill and the Tone River",
    ],
    [
      "A Frank Encampment in the Desert of Mount Sinai. 1842 - The Convent of St. Catherine in the Distance",
      "A Frank Encampment in the Desert of Mount Sinai",
    ],
  ].map(([k, v]) => [k.normalize("NFC"), v]),
);

/** Abbreviations whose trailing period is part of the word — never
 *  strip when the title ends with one. */
const TRAILING_ABBREV_RX =
  /\b(Mr|Mrs|Ms|Dr|St|Sr|Jr|Inc|Co|Ltd|fl|ca|cm|in|d\. ?J|d\. ?Ä|etc|vs|Ave|Blvd|i\.e|e\.g)\.$/i;

function formatTitle(rawTitle: string, artist?: string): string {
  let t = rawTitle.trim();

  const rewrite = TITLE_REWRITES.get(t.normalize("NFC"));
  if (rewrite) return rewrite;

  const labelMatch = t.match(/label QS:L\w+,"([^"]+)"/);
  if (labelMatch) t = labelMatch[1];
  const labelCut = t.indexOf(" label QS:");
  if (labelCut > 0) t = t.slice(0, labelCut).trim();

  const altIdx = t.indexOf(`" Alternative title:`);
  if (altIdx > 0) {
    t = t.slice(0, altIdx).trim();
    if (t.startsWith(`"`)) t = t.slice(1).trim();
  }
  const altIdx2 = t.indexOf("Alternative title");
  if (altIdx2 > 0)
    t = t
      .slice(0, altIdx2)
      .replace(/[":\s]+$/, "")
      .trim();

  const seriesIdx = t.indexOf(", from the series ");
  if (seriesIdx > 0) t = t.slice(0, seriesIdx).trim();

  t = t.replace(/\s+-\s+Google Art Project$/i, "");
  t = t.replace(/\s+-\s+Google Cultural Institute$/i, "");
  t = t.replace(/\s+C2RMF(\s+retouched)?\s*$/i, "");
  t = t.replace(/\.jpe?g$/i, "");
  t = t.replace(/^\d+px-/, "");

  // "Artist - Title" prefix — if the title leads with the artist's
  // name (or just their last token) followed by a separator, drop it
  // (the byline already shows the artist). Tries the full name first,
  // then falls back to the last whitespace-separated token so dataset
  // shorthand like "Turner - The Eruption…" (artist field "J. M. W.
  // Turner") is also caught.
  if (artist) {
    const a = artist.trim();
    if (a.length > 1) {
      const fullPrefix = `${a} - `;
      if (t.toLowerCase().startsWith(fullPrefix.toLowerCase())) {
        t = t.slice(fullPrefix.length).trim();
      } else {
        const tokens = a.split(/\s+/);
        const last = tokens[tokens.length - 1];
        if (last && last.length > 2) {
          const lastPrefix = `${last} - `;
          if (t.toLowerCase().startsWith(lastPrefix.toLowerCase())) {
            t = t.slice(lastPrefix.length).trim();
          }
        }
      }
    }
  }

  const audubonMatch = t.match(/^(\d{2,4})\s+I\.\s+(.+)$/);
  if (audubonMatch) {
    const plateNum = audubonMatch[1];
    const rest = audubonMatch[2];
    const items = rest.split(/\s*-\s*\d+\.\s*/);
    const first = items[0]?.trim();
    const more = items.length - 1;
    if (first) {
      t = more > 0 ? `Plate ${plateNum}: ${first} (+${more} more)` : `Plate ${plateNum}: ${first}`;
    }
  }

  t = t
    .replace(/_/g, " ")
    .replace(/\s{2,}/g, " ")
    .trim();

  // Trailing period — many descriptive titles end in `.` because the
  // source treated them as sentences; museum convention is to omit
  // it. Skip well-known abbreviations so "Holbein d. J." and "St."
  // aren't truncated.
  if (t.endsWith(".") && !t.endsWith("..") && !TRAILING_ABBREV_RX.test(t)) {
    t = t.slice(0, -1).trim();
  }

  return t;
}

/** Format the artist+year line for the plaque. Strips filename junk
 *  ("Foo_bar.jpg : Artist Name") and dedupes repeated attributions
 *  from comma/slash-separated artist fields. */
function formatByline(artwork: Artwork): string {
  let artist = artwork.artist?.trim() ?? "Unknown";
  if (artist.includes(".jpg") || artist.includes(".jpeg")) {
    const colonParts = artist.split(/\s*:\s*/);
    const named = colonParts.filter((p) => !/\.jpe?g/i.test(p) && p.trim().length > 0);
    if (named.length > 0) {
      const seen = new Set<string>();
      artist = named
        .filter((p) => {
          const key = p.toLowerCase();
          if (seen.has(key)) return false;
          seen.add(key);
          return true;
        })
        .join(" / ");
    }
  }
  artist = artist
    .replace(/derivative work[^,]*$/i, "")
    .trim()
    .replace(/[,/]\s*$/, "");

  const slashParts = artist.split(/\s*\/\s*/);
  if (slashParts.length > 2) {
    artist = `${slashParts[0]} et al.`;
  }

  const year = artwork.year ? String(artwork.year) : "";
  return year ? `${artist}, ${year}` : artist;
}

function PaintingPlane({
  url,
  widthM,
  heightM,
  artwork,
  onLoaded,
  onTextureAspect,
}: {
  url: string;
  widthM: number;
  heightM: number;
  artwork: Placement["artwork"];
  onLoaded?: () => void;
  /** Reports the loaded texture's true pixel aspect (w/h). Parent uses
   *  this to refit the plane + frame to the texture's real shape, so a
   *  bad realDimensions value can't visibly distort the painting. */
  onTextureAspect?: (aspect: number) => void;
}) {
  const texture = useCachedTexture(url);
  const meshRef = useRef<THREE.Mesh>(null);
  const matRef = useRef<THREE.MeshBasicMaterial>(null);
  const { gl } = useThree();

  // PaintingPlane only mounts after Suspense resolves — i.e. after the
  // 960 px texture is decoded and uploaded. Fire once so the parent can
  // tally progress for the start-overlay "Loading first room…" bar.
  // biome-ignore lint/correctness/useExhaustiveDependencies: one-shot — onLoaded identity changes shouldn't refire.
  useEffect(() => {
    onLoaded?.();
  }, []);

  // Report the loaded texture's pixel aspect once. The same aspect
  // applies to every LOD tier (they're rescaled copies of the same
  // source), so we only need the base 960 px load. If realDimensions
  // disagrees with what the player actually sees, the parent fits the
  // plane to this aspect.
  useEffect(() => {
    const img = texture.image as { width?: number; height?: number } | undefined;
    if (!img || !img.width || !img.height) return;
    onTextureAspect?.(img.width / img.height);
  }, [texture, onTextureAspect]);

  useEffect(() => {
    const mesh = meshRef.current;
    const material = matRef.current;
    if (!mesh || !material) return;

    // Skip tiers whose variant wasn't generated for this artwork. If
    // the source is only 1800 px, the 1920/2560/4096 tiers never built —
    // no point fetching a 404 each time the player walks by.
    const available = new Set(artwork.variantWidths ?? []);
    const tiers = LOD_TIERS.filter((t) => available.has(t.width));
    const tierUrls = tiers.map((t) => variantUrl(artwork.objectKey, t.width, "avif"));
    const pending: (AbortController | null)[] = tiers.map(() => null);
    // -1 = base 960 px; otherwise an index into `tiers`.
    let displayedTier = -1;

    const lodUpdate = (distSq: number) => {
      // Prefetch each tier as the player enters its radius. getHiRes
      // (used as our "is it cached?" check) touches MRU as a side effect,
      // so prefetched tiers stay alive in the LRU as long as we're still
      // in their prefetch radius — they only become eviction candidates
      // once the player walks past the release boundary.
      for (let i = 0; i < tiers.length; i++) {
        const tier = tiers[i];
        if (distSq < tier.prefetchSq && !pending[i] && getHiRes(tierUrls[i]) === undefined) {
          const ctl = new AbortController();
          pending[i] = ctl;
          loadHiRes(tierUrls[i], gl, ctl.signal)
            .catch(() => {})
            .finally(() => {
              if (pending[i] === ctl) pending[i] = null;
            });
        }
      }

      // Pick the highest tier we should display: walk highest → lowest,
      // upgrade if we're inside upgradeSq, or hold our current tier if
      // we're still inside its downgradeSq (hysteresis). First match
      // wins.
      let targetTier = -1;
      for (let i = 0; i < tiers.length; i++) {
        const tier = tiers[i];
        const want = (displayedTier === i && distSq < tier.downgradeSq) || distSq < tier.upgradeSq;
        if (!want) continue;
        const tex = getHiRes(tierUrls[i]); // touches MRU → pins it
        if (tex) {
          targetTier = i;
          break;
        }
      }

      if (targetTier !== displayedTier) {
        material.map = targetTier === -1 ? texture : (getHiRes(tierUrls[targetTier]) ?? texture);
        material.needsUpdate = true;
        displayedTier = targetTier;
      }

      // Past the release radius for a given tier — abort any pending
      // fetch. The texture (if any was placed in the LRU before we
      // got here) is left to age out naturally.
      for (let i = 0; i < tiers.length; i++) {
        if (distSq > tiers[i].releaseSq) {
          const ctl = pending[i];
          if (ctl) {
            ctl.abort();
            pending[i] = null;
          }
        }
      }
    };

    const entry: PaintingEntry = {
      mesh,
      worldPos: mesh.getWorldPosition(new THREE.Vector3()),
      artwork,
      lodUpdate,
    };
    registerPainting(entry);
    return () => {
      unregisterPainting(entry);
      for (const ctl of pending) ctl?.abort();
    };
  }, [artwork, texture, gl]);

  return (
    <mesh ref={meshRef} position={[0, 0, 0.014]} userData={{ artwork }}>
      <planeGeometry args={[widthM, heightM]} />
      <meshBasicMaterial ref={matRef} map={texture} toneMapped={false} />
    </mesh>
  );
}

/** Shown while the real texture is still fetching. Eagerly loads the
 *  smallest available variant (256 px) and shows it as soon as it
 *  arrives — typically a few hundred milliseconds before the 960 px
 *  base resolves. Means a fresh floor renders with low-res images
 *  almost immediately instead of a wall of brown swatches, while the
 *  high-res tier streams in behind the Suspense boundary. */
function FallbackSwatch({
  widthM,
  heightM,
  artwork,
}: {
  widthM: number;
  heightM: number;
  artwork: Placement["artwork"];
}) {
  const meshRef = useRef<THREE.Mesh>(null);
  const [thumb, setThumb] = useState<THREE.Texture | null>(null);

  useEffect(() => {
    const mesh = meshRef.current;
    if (!mesh) return;
    const entry: PaintingEntry = {
      mesh,
      worldPos: mesh.getWorldPosition(new THREE.Vector3()),
      artwork,
    };
    registerPainting(entry);
    return () => unregisterPainting(entry);
  }, [artwork]);

  useEffect(() => {
    // Skip if the artwork has no 256 variant (some scrape sources
    // produced sub-256 px originals and stop at the largest available
    // variant).
    const widths = artwork.variantWidths;
    if (widths && !widths.includes(256)) return;
    const url = variantUrl(artwork.objectKey, 256, "avif");
    let cancelled = false;
    const loader = new THREE.TextureLoader();
    loader.load(
      url,
      (tex) => {
        if (cancelled) {
          tex.dispose();
          return;
        }
        tex.colorSpace = THREE.SRGBColorSpace;
        setThumb(tex);
      },
      undefined,
      () => {
        // Variant might 404 if the manifest is stale — fall back to
        // the brown swatch silently.
      },
    );
    return () => {
      cancelled = true;
    };
  }, [artwork]);

  // Free the thumb texture when the swatch unmounts (Suspense unwrap or
  // floor swap). Without this, every fallback render leaks one tiny
  // texture into VRAM that the LRU never sees.
  useEffect(
    () => () => {
      thumb?.dispose();
    },
    [thumb],
  );

  return (
    <mesh ref={meshRef} position={[0, 0, 0.014]} userData={{ artwork }}>
      <planeGeometry args={[widthM, heightM]} />
      {thumb ? (
        <meshBasicMaterial map={thumb} toneMapped={false} />
      ) : (
        <meshBasicMaterial color="#3a2e20" toneMapped={false} />
      )}
    </mesh>
  );
}

/** Stand-in plane for an NSFW painting when the user has chosen
 *  hide / blur. Registers with the painting-registry so the
 *  player's aim raycast still resolves and they can press E to
 *  inspect (the zoom modal then shows the actual artwork — same
 *  reveal flow as the 2D gallery's blur overlay). v1: a flat
 *  colour swatch tinted slightly differently from the loading
 *  fallback so the player can read "intentionally hidden" vs
 *  "still loading". */
function NsfwPlaceholder({
  widthM,
  heightM,
  artwork,
  mode,
  onLoaded,
}: {
  widthM: number;
  heightM: number;
  artwork: Placement["artwork"];
  mode: "hide" | "blur" | "show";
  onLoaded?: () => void;
}) {
  const meshRef = useRef<THREE.Mesh>(null);

  useEffect(() => {
    const mesh = meshRef.current;
    if (!mesh) return;
    const entry: PaintingEntry = {
      mesh,
      worldPos: mesh.getWorldPosition(new THREE.Vector3()),
      artwork,
    };
    registerPainting(entry);
    return () => unregisterPainting(entry);
  }, [artwork]);

  // Tally the "loaded" callback the same as a real painting does —
  // the entry-room progress bar measures total painting slots, not
  // texture decodes per se, and a placeholder is "ready" instantly.
  // biome-ignore lint/correctness/useExhaustiveDependencies: one-shot, mirroring PaintingPlane's behaviour
  useEffect(() => {
    onLoaded?.();
  }, []);

  const color = mode === "hide" ? "#241a14" : "#4a3a2c";

  return (
    <mesh ref={meshRef} position={[0, 0, 0.014]} userData={{ artwork }}>
      <planeGeometry args={[widthM, heightM]} />
      <meshBasicMaterial color={color} toneMapped={false} />
    </mesh>
  );
}
