"use client";

import type { Artwork } from "@/lib/data";
import type { Placement } from "@/lib/gallery-layout/types";
import { variantUrl } from "@/lib/utils";
import { Text } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import { Suspense, useEffect, useRef } from "react";
import * as THREE from "three";
import { type PaintingEntry, registerPainting, unregisterPainting } from "./painting-registry";
import {
  FRAME_VARIANTS,
  type FrameVariantId,
  plaqueBaseMaterial,
  plaqueMountMaterial,
} from "./palette-materials";
import { getHiRes, loadHiRes, useCachedTexture } from "./texture-cache";

/**
 * One painting on a wall. Renders a thin box behind the canvas so the
 * painting has some depth (the wall behind is roughly 0.05 m away),
 * with a textured plane on the front. Registers itself with the
 * global painting-registry so the Player's aim raycast can skip the
 * full scene traversal.
 *
 * Prefer a 960 px variant — big enough to look crisp at 2 m wide, small
 * enough that a few hundred paintings on a floor fit in GPU memory
 * comfortably. The texture-cache handles LRU eviction + rAF-paced GPU
 * uploads so a floor-wide burst of loads doesn't hitch the frame.
 */
// Tiered proximity LOD. Each tier names a variant width and four
// distance bands:
//
//   prefetch ─ start the network fetch eagerly so the swap feels
//              instantaneous when the player crosses upgrade.
//   upgrade  ─ first time we display this tier (must be cached).
//   downgrade ─ hysteresis: keep displaying once selected until the
//              player retreats past this radius.
//   release  ─ abort any in-flight fetch past this distance.
//
// Tiers are listed highest → lowest. The base 960 px texture is
// always loaded by the parent <Painting>; the tiers below are
// upgrades on top of it.
//
// Bands are nested so each higher tier's window sits inside the next
// lower tier's. The 4096 px tier has the tightest, lowest-radius
// window — only used when the player is face-pressed against the
// canvas. A player walking a hallway at ~3 m/s crosses each band in
// ~150-300 ms — comfortably more than the LodController's 12-frame
// tick.
//
// Per-tier availability: each Artwork carries a `variantWidths` list
// of widths that were actually generated by `pnpm shrink` (a small
// source can't produce a 4096 px AVIF). At mount time we filter
// LOD_TIERS down to widths the artwork supports — paintings with
// small originals quietly stop at the largest available tier.
type LodTier = {
  width: number;
  prefetchSq: number;
  upgradeSq: number;
  downgradeSq: number;
  releaseSq: number;
};

const sq = (n: number) => n * n;

const LOD_TIERS: LodTier[] = [
  {
    width: 4096,
    prefetchSq: sq(1.4),
    upgradeSq: sq(0.55),
    downgradeSq: sq(0.85),
    releaseSq: sq(1.8),
  },
  {
    width: 2560,
    prefetchSq: sq(2.0),
    upgradeSq: sq(0.9),
    downgradeSq: sq(1.4),
    releaseSq: sq(3.0),
  },
  {
    width: 1920,
    prefetchSq: sq(4.0),
    upgradeSq: sq(1.8),
    downgradeSq: sq(2.8),
    releaseSq: sq(5.5),
  },
];

export function Painting({
  placement,
  onLoaded,
}: {
  placement: Placement;
  /** Fires once when the base 960 px texture has finished loading and
   *  the painting plane mounts. Used by GalleryDungeon to drive the
   *  "Loading first room…" progress bar on the start overlay. */
  onLoaded?: () => void;
}) {
  const { artwork, position, rotation, widthM, heightM } = placement;
  const url = variantUrl(artwork.objectKey, 960, "avif");

  const variant = FRAME_VARIANTS[pickFrameVariant(artwork)];
  const frameDepth = variant.depth;
  const frameInset = variant.inset;

  // Liner is a flat rim sitting on top of the frame's front face,
  // sandwiched between the frame face (at z = frameDepth/2) and the
  // canvas plane (at z = 0.014). Keep ≥1.5 mm on both sides to stay well
  // out of depth-buffer noise. Liner is canvas-sized + 2 × width in XY
  // so it's strictly inside the frame outer rectangle (no XY clipping)
  // and the canvas plane occludes its centre, leaving a visible rim.
  const linerDepth = 0.001;
  const linerClearance = 0.0015;
  const linerZ = frameDepth / 2 + linerClearance + linerDepth / 2;

  return (
    <group position={position} rotation={rotation}>
      <mesh>
        <boxGeometry args={[widthM + frameInset * 2, heightM + frameInset * 2, frameDepth]} />
        <primitive object={variant.material} attach="material" />
      </mesh>
      {variant.liner && (
        <mesh position={[0, 0, linerZ]}>
          <boxGeometry
            args={[widthM + variant.liner.width * 2, heightM + variant.liner.width * 2, linerDepth]}
          />
          <primitive object={variant.liner.material} attach="material" />
        </mesh>
      )}
      <Suspense fallback={<FallbackSwatch widthM={widthM} heightM={heightM} artwork={artwork} />}>
        <PaintingPlane
          url={url}
          widthM={widthM}
          heightM={heightM}
          artwork={artwork}
          onLoaded={onLoaded}
        />
      </Suspense>
      <Plaque artwork={artwork} widthM={widthM} />
    </group>
  );
}

// Pick a frame variant that complements the painting's era. Each rule
// below is a substring match against the artwork's `movement` field —
// some entries in the dataset are slashed combos like "Realism /
// Impressionism", so the first match wins. Anything unmatched (and the
// non-trivial number of artworks with `movement: null`) falls through to
// a stable hash on the artwork id, which keeps a consistent look per
// painting across reloads while still spreading variety across the
// gallery.
function pickFrameVariant(artwork: Artwork): FrameVariantId {
  const m = artwork.movement;
  if (m) {
    if (m.includes("Ukiyo-e")) return "redLacquer";
    if (
      m.includes("Renaissance") ||
      m.includes("Baroque") ||
      m.includes("Mannerism") ||
      m.includes("Academicism") ||
      m.includes("Neoclassicism")
    )
      return "gilded";
    if (
      m.includes("Impressionism") ||
      m.includes("Pre-Raphaelite") ||
      m.includes("Art Nouveau") ||
      m.includes("Neo-Impressionism")
    )
      return "paleAsh";
    if (
      m.includes("Modernism") ||
      m.includes("Fauvism") ||
      m.includes("Post-Impressionism") ||
      m.includes("Symbolism") ||
      m.includes("Expressionism")
    )
      return "ebony";
    if (
      m.includes("Dutch Golden Age") ||
      m.includes("Realism") ||
      m.includes("Romanticism") ||
      m.includes("Tonalism") ||
      m.includes("Regionalism")
    )
      return "walnut";
  }
  // Stable hash → deterministic per id, distributed across all five.
  const order: FrameVariantId[] = ["walnut", "ebony", "paleAsh", "gilded", "redLacquer"];
  let h = 0;
  for (let i = 0; i < artwork.id.length; i++) h = (h * 31 + artwork.id.charCodeAt(i)) | 0;
  return order[Math.abs(h) % order.length];
}

// ── Plaque ────────────────────────────────────────────────────────────
// A small museum-style label to the right of each painting at canvas
// centre height. Two-layer construction: a brass mount plate fixed
// flush to the wall, with a slightly inset cream face card on top
// carrying title / artist / year / dimensions in three sized lines.

// Cream face dims. Painting + plaque reach (painting width / 2 + GAP
// + face / 2) stays under ~1.25 m so neighbouring paintings don't
// collide.
const PLAQUE_FACE_W = 0.28;
const PLAQUE_FACE_H = 0.18;
const PLAQUE_FACE_DEPTH = 0.004;
// Brushed-steel mount sits a hair larger than the face, framing it
// like a polished metal rim. Bigger reveal here makes the shimmer
// from the mount more visible at typical viewing distances.
const PLAQUE_MOUNT_W = PLAQUE_FACE_W + 0.028;
const PLAQUE_MOUNT_H = PLAQUE_FACE_H + 0.028;
const PLAQUE_MOUNT_DEPTH = 0.008;
const PLAQUE_GAP = 0.06;
// `placement.position` is offset PAINTING_WALL_OFFSET (= 0.02 m) into
// the room from the wall plane, so localZ = -0.02 lands the plaque
// back exactly on the wall surface. Keep this in sync with
// PAINTING_WALL_OFFSET in src/lib/gallery-layout/place-paintings.ts.
const PAINTING_WALL_OFFSET = 0.02;
// Small clearance so the plaque mount's back doesn't sit coplanar with
// the wall — coplanar geometry z-fights from any camera and shows
// through DoubleSide walls as wedge-shaped artefacts. 5 mm is enough
// for far-room viewing without making the plaque look detached.
const PLAQUE_WALL_CLEAR = 0.005;

function Plaque({
  artwork,
  widthM,
}: {
  artwork: Artwork;
  widthM: number;
}) {
  const localX = widthM / 2 + PLAQUE_GAP + PLAQUE_MOUNT_W / 2;
  const localY = 0;
  // Mount sits a few mm off the wall so it doesn't z-fight with it; face
  // is parked just in front of the mount; text floats a hair above the
  // face for the same reason.
  const mountCenterZ = -PAINTING_WALL_OFFSET + PLAQUE_WALL_CLEAR + PLAQUE_MOUNT_DEPTH / 2;
  const faceCenterZ = mountCenterZ + PLAQUE_MOUNT_DEPTH / 2 + PLAQUE_FACE_DEPTH / 2;
  const textZ = faceCenterZ + PLAQUE_FACE_DEPTH / 2 + 0.001;

  const title = stripBrackets(artwork.title);
  const artist = artwork.artist ?? "Unknown";
  const year = artwork.year ? String(artwork.year) : "";
  const byline = year ? `${artist}, ${year}` : artist;
  const dims = artwork.realDimensions
    ? `${artwork.realDimensions.widthCm.toFixed(0)} × ${artwork.realDimensions.heightCm.toFixed(0)} cm`
    : "";

  return (
    <group position={[localX, localY, 0]}>
      {/* Brass mount plate */}
      <mesh position={[0, 0, mountCenterZ]}>
        <boxGeometry args={[PLAQUE_MOUNT_W, PLAQUE_MOUNT_H, PLAQUE_MOUNT_DEPTH]} />
        <primitive object={plaqueMountMaterial} attach="material" />
      </mesh>
      {/* Cream face card on top of the mount */}
      <mesh position={[0, 0, faceCenterZ]}>
        <boxGeometry args={[PLAQUE_FACE_W, PLAQUE_FACE_H, PLAQUE_FACE_DEPTH]} />
        <primitive object={plaqueBaseMaterial} attach="material" />
      </mesh>
      {/* Title — bold and largest. */}
      <Text
        position={[0, PLAQUE_FACE_H * 0.28, textZ]}
        fontSize={0.022}
        lineHeight={1.15}
        color="#0d0a08"
        fontWeight={700}
        anchorX="center"
        anchorY="middle"
        maxWidth={PLAQUE_FACE_W - 0.022}
        textAlign="center"
      >
        {title}
      </Text>
      {/* Artist · year */}
      <Text
        position={[0, 0, textZ]}
        fontSize={0.018}
        lineHeight={1.2}
        color="#1c1410"
        anchorX="center"
        anchorY="middle"
        maxWidth={PLAQUE_FACE_W - 0.022}
        textAlign="center"
      >
        {byline}
      </Text>
      {/* Dimensions — smaller, slightly lighter. */}
      {dims && (
        <Text
          position={[0, -PLAQUE_FACE_H * 0.32, textZ]}
          fontSize={0.014}
          lineHeight={1.15}
          color="#3a2c22"
          anchorX="center"
          anchorY="middle"
          maxWidth={PLAQUE_FACE_W - 0.022}
          textAlign="center"
        >
          {dims}
        </Text>
      )}
    </group>
  );
}

/** Trim Wikimedia title noise: `label QS:Len,"Foo"` → `Foo`, drop
 *  trailing language-tagged duplicates. */
function stripBrackets(title: string): string {
  const m = title.match(/label QS:L\w+,"([^"]+)"/);
  if (m) return m[1];
  const cut = title.indexOf(" label QS:");
  if (cut > 0) return title.slice(0, cut).trim();
  return title;
}

function PaintingPlane({
  url,
  widthM,
  heightM,
  artwork,
  onLoaded,
}: {
  url: string;
  widthM: number;
  heightM: number;
  artwork: Placement["artwork"];
  onLoaded?: () => void;
}) {
  const texture = useCachedTexture(url);
  const meshRef = useRef<THREE.Mesh>(null);
  const matRef = useRef<THREE.MeshBasicMaterial>(null);
  const { gl } = useThree();

  // PaintingPlane only mounts after Suspense resolves — i.e. after the
  // 960 px texture is decoded and uploaded. Fire once so the parent can
  // tally progress for the start-overlay "Loading first room…" bar.
  // biome-ignore lint/correctness/useExhaustiveDependencies: one-shot — onLoaded identity changes shouldn't refire.
  useEffect(() => {
    onLoaded?.();
  }, []);

  useEffect(() => {
    const mesh = meshRef.current;
    const material = matRef.current;
    if (!mesh || !material) return;

    // Skip tiers whose variant wasn't generated for this artwork. If
    // the source is only 1800 px, the 1920/2560/4096 tiers never built —
    // no point fetching a 404 each time the player walks by.
    const available = new Set(artwork.variantWidths ?? []);
    const tiers = LOD_TIERS.filter((t) => available.has(t.width));
    const tierUrls = tiers.map((t) => variantUrl(artwork.objectKey, t.width, "avif"));
    const pending: (AbortController | null)[] = tiers.map(() => null);
    // -1 = base 960 px; otherwise an index into `tiers`.
    let displayedTier = -1;

    const lodUpdate = (distSq: number) => {
      // Prefetch each tier as the player enters its radius. getHiRes
      // (used as our "is it cached?" check) touches MRU as a side effect,
      // so prefetched tiers stay alive in the LRU as long as we're still
      // in their prefetch radius — they only become eviction candidates
      // once the player walks past the release boundary.
      for (let i = 0; i < tiers.length; i++) {
        const tier = tiers[i];
        if (distSq < tier.prefetchSq && !pending[i] && getHiRes(tierUrls[i]) === undefined) {
          const ctl = new AbortController();
          pending[i] = ctl;
          loadHiRes(tierUrls[i], gl, ctl.signal)
            .catch(() => {})
            .finally(() => {
              if (pending[i] === ctl) pending[i] = null;
            });
        }
      }

      // Pick the highest tier we should display: walk highest → lowest,
      // upgrade if we're inside upgradeSq, or hold our current tier if
      // we're still inside its downgradeSq (hysteresis). First match
      // wins.
      let targetTier = -1;
      for (let i = 0; i < tiers.length; i++) {
        const tier = tiers[i];
        const want = (displayedTier === i && distSq < tier.downgradeSq) || distSq < tier.upgradeSq;
        if (!want) continue;
        const tex = getHiRes(tierUrls[i]); // touches MRU → pins it
        if (tex) {
          targetTier = i;
          break;
        }
      }

      if (targetTier !== displayedTier) {
        material.map = targetTier === -1 ? texture : (getHiRes(tierUrls[targetTier]) ?? texture);
        material.needsUpdate = true;
        displayedTier = targetTier;
      }

      // Past the release radius for a given tier — abort any pending
      // fetch. The texture (if any was placed in the LRU before we
      // got here) is left to age out naturally.
      for (let i = 0; i < tiers.length; i++) {
        if (distSq > tiers[i].releaseSq) {
          const ctl = pending[i];
          if (ctl) {
            ctl.abort();
            pending[i] = null;
          }
        }
      }
    };

    const entry: PaintingEntry = {
      mesh,
      worldPos: mesh.getWorldPosition(new THREE.Vector3()),
      artwork,
      lodUpdate,
    };
    registerPainting(entry);
    return () => {
      unregisterPainting(entry);
      for (const ctl of pending) ctl?.abort();
    };
  }, [artwork, texture, gl]);

  return (
    <mesh ref={meshRef} position={[0, 0, 0.014]} userData={{ artwork }}>
      <planeGeometry args={[widthM, heightM]} />
      <meshBasicMaterial ref={matRef} map={texture} toneMapped={false} />
    </mesh>
  );
}

/** Shown while the real texture is still fetching. */
function FallbackSwatch({
  widthM,
  heightM,
  artwork,
}: {
  widthM: number;
  heightM: number;
  artwork: Placement["artwork"];
}) {
  const meshRef = useRef<THREE.Mesh>(null);

  useEffect(() => {
    const mesh = meshRef.current;
    if (!mesh) return;
    const entry: PaintingEntry = {
      mesh,
      worldPos: mesh.getWorldPosition(new THREE.Vector3()),
      artwork,
    };
    registerPainting(entry);
    return () => unregisterPainting(entry);
  }, [artwork]);

  return (
    <mesh ref={meshRef} position={[0, 0, 0.014]} userData={{ artwork }}>
      <planeGeometry args={[widthM, heightM]} />
      <meshBasicMaterial color="#3a2e20" toneMapped={false} />
    </mesh>
  );
}
