"use client";

import type { Artwork } from "@/lib/data";
import type { Placement } from "@/lib/gallery-layout/types";
import { variantUrl } from "@/lib/utils";
import { Text } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import { Suspense, useEffect, useRef } from "react";
import * as THREE from "three";
import { type PaintingEntry, registerPainting, unregisterPainting } from "./painting-registry";
import { frameMaterial, plaqueBaseMaterial, plaqueMountMaterial } from "./palette-materials";
import { getHiRes, loadHiRes, useCachedTexture } from "./texture-cache";

/**
 * One painting on a wall. Renders a thin box behind the canvas so the
 * painting has some depth (the wall behind is roughly 0.05 m away),
 * with a textured plane on the front. Registers itself with the
 * global painting-registry so the Player's aim raycast can skip the
 * full scene traversal.
 *
 * Prefer a 960 px variant — big enough to look crisp at 2 m wide, small
 * enough that a few hundred paintings on a floor fit in GPU memory
 * comfortably. The texture-cache handles LRU eviction + rAF-paced GPU
 * uploads so a floor-wide burst of loads doesn't hitch the frame.
 */
// Tiered proximity LOD. Each tier names a variant width and four
// distance bands:
//
//   prefetch ─ start the network fetch eagerly so the swap feels
//              instantaneous when the player crosses upgrade.
//   upgrade  ─ first time we display this tier (must be cached).
//   downgrade ─ hysteresis: keep displaying once selected until the
//              player retreats past this radius.
//   release  ─ abort any in-flight fetch past this distance.
//
// Tiers are listed highest → lowest. The base 960 px texture is
// always loaded by the parent <Painting>; the tiers below are
// upgrades on top of it.
//
// Bands are nested so each higher tier's window sits inside the next
// lower tier's. The 4096 px tier has the tightest, lowest-radius
// window — only used when the player is face-pressed against the
// canvas. A player walking a hallway at ~3 m/s crosses each band in
// ~150-300 ms — comfortably more than the LodController's 12-frame
// tick.
//
// Per-tier availability: each Artwork carries a `variantWidths` list
// of widths that were actually generated by `pnpm shrink` (a small
// source can't produce a 4096 px AVIF). At mount time we filter
// LOD_TIERS down to widths the artwork supports — paintings with
// small originals quietly stop at the largest available tier.
type LodTier = {
  width: number;
  prefetchSq: number;
  upgradeSq: number;
  downgradeSq: number;
  releaseSq: number;
};

const sq = (n: number) => n * n;

const LOD_TIERS: LodTier[] = [
  {
    width: 4096,
    prefetchSq: sq(1.4),
    upgradeSq: sq(0.55),
    downgradeSq: sq(0.85),
    releaseSq: sq(1.8),
  },
  {
    width: 2560,
    prefetchSq: sq(2.0),
    upgradeSq: sq(0.9),
    downgradeSq: sq(1.4),
    releaseSq: sq(3.0),
  },
  {
    width: 1920,
    prefetchSq: sq(4.0),
    upgradeSq: sq(1.8),
    downgradeSq: sq(2.8),
    releaseSq: sq(5.5),
  },
];

export function Painting({ placement }: { placement: Placement }) {
  const { artwork, position, rotation, widthM, heightM } = placement;
  const url = variantUrl(artwork.objectKey, 960, "avif");

  // Frame depth was 5 cm — visibly chunky from oblique angles, made
  // paintings look like they were floating off the wall. Real museum
  // frames are 2-3 cm; matching that hides the boxiness.
  const frameDepth = 0.025;
  const frameInset = 0.025;

  return (
    <group position={position} rotation={rotation}>
      <mesh>
        <boxGeometry args={[widthM + frameInset * 2, heightM + frameInset * 2, frameDepth]} />
        <primitive object={frameMaterial} attach="material" />
      </mesh>
      <Suspense fallback={<FallbackSwatch widthM={widthM} heightM={heightM} artwork={artwork} />}>
        <PaintingPlane url={url} widthM={widthM} heightM={heightM} artwork={artwork} />
      </Suspense>
      <Plaque artwork={artwork} widthM={widthM} />
    </group>
  );
}

// ── Plaque ────────────────────────────────────────────────────────────
// A small museum-style label to the right of each painting at canvas
// centre height. Two-layer construction: a brass mount plate fixed
// flush to the wall, with a slightly inset cream face card on top
// carrying title / artist / year / dimensions in three sized lines.

// Cream face dims. Painting + plaque reach (painting width / 2 + GAP
// + face / 2) stays under ~1.25 m so neighbouring paintings don't
// collide.
const PLAQUE_FACE_W = 0.21;
const PLAQUE_FACE_H = 0.13;
const PLAQUE_FACE_DEPTH = 0.004;
// Brass mount sits a hair larger than the face, acting as a visible
// frame rim around it.
const PLAQUE_MOUNT_W = PLAQUE_FACE_W + 0.018;
const PLAQUE_MOUNT_H = PLAQUE_FACE_H + 0.018;
const PLAQUE_MOUNT_DEPTH = 0.006;
const PLAQUE_GAP = 0.06;
// `placement.position` is offset PAINTING_WALL_OFFSET (= 0.06 m) into
// the room from the wall plane, so localZ = -0.06 lands the plaque
// back exactly on the wall surface.
const PAINTING_WALL_OFFSET = 0.06;

function Plaque({
  artwork,
  widthM,
}: {
  artwork: Artwork;
  widthM: number;
}) {
  const localX = widthM / 2 + PLAQUE_GAP + PLAQUE_MOUNT_W / 2;
  const localY = 0;
  // Mount sits flush against the wall; face is parked just in front
  // of it; text floats a hair above the face to clear z-fighting.
  const mountCenterZ = -PAINTING_WALL_OFFSET + PLAQUE_MOUNT_DEPTH / 2;
  const faceCenterZ = mountCenterZ + PLAQUE_MOUNT_DEPTH / 2 + PLAQUE_FACE_DEPTH / 2;
  const textZ = faceCenterZ + PLAQUE_FACE_DEPTH / 2 + 0.001;

  const title = stripBrackets(artwork.title);
  const artist = artwork.artist ?? "Unknown";
  const year = artwork.year ? String(artwork.year) : "";
  const byline = year ? `${artist}, ${year}` : artist;
  const dims = artwork.realDimensions
    ? `${artwork.realDimensions.widthCm.toFixed(0)} × ${artwork.realDimensions.heightCm.toFixed(0)} cm`
    : "";

  return (
    <group position={[localX, localY, 0]}>
      {/* Brass mount plate */}
      <mesh position={[0, 0, mountCenterZ]}>
        <boxGeometry args={[PLAQUE_MOUNT_W, PLAQUE_MOUNT_H, PLAQUE_MOUNT_DEPTH]} />
        <primitive object={plaqueMountMaterial} attach="material" />
      </mesh>
      {/* Cream face card on top of the mount */}
      <mesh position={[0, 0, faceCenterZ]}>
        <boxGeometry args={[PLAQUE_FACE_W, PLAQUE_FACE_H, PLAQUE_FACE_DEPTH]} />
        <primitive object={plaqueBaseMaterial} attach="material" />
      </mesh>
      {/* Title — small caps weight, italic-ish via slight emphasis */}
      <Text
        position={[0, PLAQUE_FACE_H * 0.28, textZ]}
        fontSize={0.014}
        lineHeight={1.2}
        color="#1a1108"
        fontWeight={600}
        anchorX="center"
        anchorY="middle"
        maxWidth={PLAQUE_FACE_W - 0.018}
        textAlign="center"
      >
        {title}
      </Text>
      {/* Artist · year */}
      <Text
        position={[0, 0, textZ]}
        fontSize={0.011}
        lineHeight={1.25}
        color="#3a2a1f"
        anchorX="center"
        anchorY="middle"
        maxWidth={PLAQUE_FACE_W - 0.018}
        textAlign="center"
      >
        {byline}
      </Text>
      {/* Dimensions — smaller, lighter */}
      {dims && (
        <Text
          position={[0, -PLAQUE_FACE_H * 0.32, textZ]}
          fontSize={0.0095}
          lineHeight={1.2}
          color="#5a463a"
          anchorX="center"
          anchorY="middle"
          maxWidth={PLAQUE_FACE_W - 0.018}
          textAlign="center"
        >
          {dims}
        </Text>
      )}
    </group>
  );
}

/** Trim Wikimedia title noise: `label QS:Len,"Foo"` → `Foo`, drop
 *  trailing language-tagged duplicates. */
function stripBrackets(title: string): string {
  const m = title.match(/label QS:L\w+,"([^"]+)"/);
  if (m) return m[1];
  const cut = title.indexOf(" label QS:");
  if (cut > 0) return title.slice(0, cut).trim();
  return title;
}

function PaintingPlane({
  url,
  widthM,
  heightM,
  artwork,
}: {
  url: string;
  widthM: number;
  heightM: number;
  artwork: Placement["artwork"];
}) {
  const texture = useCachedTexture(url);
  const meshRef = useRef<THREE.Mesh>(null);
  const matRef = useRef<THREE.MeshBasicMaterial>(null);
  const { gl } = useThree();

  useEffect(() => {
    const mesh = meshRef.current;
    const material = matRef.current;
    if (!mesh || !material) return;

    // Skip tiers whose variant wasn't generated for this artwork. If
    // the source is only 1800 px, the 1920/2560/4096 tiers never built —
    // no point fetching a 404 each time the player walks by.
    const available = new Set(artwork.variantWidths ?? []);
    const tiers = LOD_TIERS.filter((t) => available.has(t.width));
    const tierUrls = tiers.map((t) => variantUrl(artwork.objectKey, t.width, "avif"));
    const pending: (AbortController | null)[] = tiers.map(() => null);
    // -1 = base 960 px; otherwise an index into `tiers`.
    let displayedTier = -1;

    const lodUpdate = (distSq: number) => {
      // Prefetch each tier as the player enters its radius. getHiRes
      // (used as our "is it cached?" check) touches MRU as a side effect,
      // so prefetched tiers stay alive in the LRU as long as we're still
      // in their prefetch radius — they only become eviction candidates
      // once the player walks past the release boundary.
      for (let i = 0; i < tiers.length; i++) {
        const tier = tiers[i];
        if (distSq < tier.prefetchSq && !pending[i] && getHiRes(tierUrls[i]) === undefined) {
          const ctl = new AbortController();
          pending[i] = ctl;
          loadHiRes(tierUrls[i], gl, ctl.signal)
            .catch(() => {})
            .finally(() => {
              if (pending[i] === ctl) pending[i] = null;
            });
        }
      }

      // Pick the highest tier we should display: walk highest → lowest,
      // upgrade if we're inside upgradeSq, or hold our current tier if
      // we're still inside its downgradeSq (hysteresis). First match
      // wins.
      let targetTier = -1;
      for (let i = 0; i < tiers.length; i++) {
        const tier = tiers[i];
        const want = (displayedTier === i && distSq < tier.downgradeSq) || distSq < tier.upgradeSq;
        if (!want) continue;
        const tex = getHiRes(tierUrls[i]); // touches MRU → pins it
        if (tex) {
          targetTier = i;
          break;
        }
      }

      if (targetTier !== displayedTier) {
        material.map = targetTier === -1 ? texture : (getHiRes(tierUrls[targetTier]) ?? texture);
        material.needsUpdate = true;
        displayedTier = targetTier;
      }

      // Past the release radius for a given tier — abort any pending
      // fetch. The texture (if any was placed in the LRU before we
      // got here) is left to age out naturally.
      for (let i = 0; i < tiers.length; i++) {
        if (distSq > tiers[i].releaseSq) {
          const ctl = pending[i];
          if (ctl) {
            ctl.abort();
            pending[i] = null;
          }
        }
      }
    };

    const entry: PaintingEntry = {
      mesh,
      worldPos: mesh.getWorldPosition(new THREE.Vector3()),
      artwork,
      lodUpdate,
    };
    registerPainting(entry);
    return () => {
      unregisterPainting(entry);
      for (const ctl of pending) ctl?.abort();
    };
  }, [artwork, texture, gl]);

  return (
    <mesh ref={meshRef} position={[0, 0, 0.014]} userData={{ artwork }}>
      <planeGeometry args={[widthM, heightM]} />
      <meshBasicMaterial ref={matRef} map={texture} toneMapped={false} />
    </mesh>
  );
}

/** Shown while the real texture is still fetching. */
function FallbackSwatch({
  widthM,
  heightM,
  artwork,
}: {
  widthM: number;
  heightM: number;
  artwork: Placement["artwork"];
}) {
  const meshRef = useRef<THREE.Mesh>(null);

  useEffect(() => {
    const mesh = meshRef.current;
    if (!mesh) return;
    const entry: PaintingEntry = {
      mesh,
      worldPos: mesh.getWorldPosition(new THREE.Vector3()),
      artwork,
    };
    registerPainting(entry);
    return () => unregisterPainting(entry);
  }, [artwork]);

  return (
    <mesh ref={meshRef} position={[0, 0, 0.014]} userData={{ artwork }}>
      <planeGeometry args={[widthM, heightM]} />
      <meshBasicMaterial color="#3a2e20" toneMapped={false} />
    </mesh>
  );
}
