#!/bin/bash

# Audubon's Birds of America Image Downloader using curl
# This script downloads all images with proper rate limiting and retry logic

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="$ROOT_DIR/assets/audubon_birds"
DELAY=3  # Seconds between downloads
MAX_RETRIES=5
RETRY_DELAY=10  # Seconds to wait before retry

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Color codes for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to calculate MD5 hash (for direct URL construction)
get_md5() {
    echo -n "$1" | md5sum | cut -d' ' -f1
}

# Function to get direct Wikimedia URL
get_direct_url() {
    local filename="$1"
    local md5=$(get_md5 "$filename")
    local a="${md5:0:1}"
    local ab="${md5:0:2}"
    echo "https://upload.wikimedia.org/wikipedia/commons/$a/$ab/$filename"
}

# Function to download a file with retry logic
download_file() {
    local filename="$1"
    local url="$2"
    local output_path="$OUTPUT_DIR/$filename"
    local retry=0
    
    while [ $retry -le $MAX_RETRIES ]; do
        curl -L -S --limit-rate 1M \
             --retry 3 --retry-delay 5 \
             -H "User-Agent: Mozilla/5.0 (compatible; EducationalProject/1.0)" \
             -f -o "$output_path" "$url" 2>/dev/null
        
        local status=$?
        
        if [ $status -eq 0 ]; then
            return 0
        elif [ $status -eq 22 ]; then
            # HTTP error (like 429)
            if [ $retry -lt $MAX_RETRIES ]; then
                retry=$((retry + 1))
                local wait_time=$((RETRY_DELAY * retry))
                echo -e "    ${YELLOW}Rate limited. Waiting ${wait_time}s before retry $retry/$MAX_RETRIES...${NC}"
                sleep $wait_time
            else
                return 1
            fi
        else
            # Other error
            return 1
        fi
    done
    
    return 1
}

# Array of all image filenames
images=(
    "1_Wild_Turkey.jpg"
    "2_Yellow-billed_Cuckoo.jpg"
    "3_Prothonotary_Warbler_restored.jpg"
    "4_Purple_Finch.jpg"
    "5_Bonaparte's_Flycatcher.jpg"
    "6_Wild_Turkey.jpg"
    "7_Purple_Grakle_or_Common_Crow_Blackbird.jpg"
    "8_White_throated_Sparrow.jpg"
    "9_Selby's_Flycatcher.jpg"
    "10_Brown_Titlark.jpg"
    "11_Bird_of_Washington.jpg"
    "12_Baltimore_Oriole.jpg"
    "13_Snow_Bird.jpg"
    "14_Prairie_Warbler.jpg"
    "15_Blue_Yellow-backed_Warbler.jpg"
    "16_Great-footed_Hawk.jpg"
    "17_Carolina_Turtle_Dove.jpg"
    "18_Bewick's_Wren.jpg"
    "19_Louisiana_Water_Thrush.jpg"
    "20_Blue-winged_Yellow_Warbler.jpg"
    "21_Mocking_Bird.jpg"
    "22_Purple_Martin.jpg"
    "23_Yellow-breasted_Warbler.jpg"
    "24_Roscoe's_Yellow-throat.jpg"
    "25_Song_Sparrow.jpg"
    "26_Carolina_Parrot.jpg"
    "27_Red_headed_Woodpecker.jpg"
    "28_Solitary_Flycatcher_or_Vireo.jpg"
    "29_Towhe_Bunting.jpg"
    "30_Vigor's_Warbler.jpg"
    "31_White-headed_Eagle.jpg"
    "32_Black-billed_Cuckoo.jpg"
    "33_American_Goldfinch.jpg"
    "34_Worm_eating_Warbler.jpg"
    "35_Children's_Warbler.jpg"
    "36_Stanley_Hawk.jpg"
    "37_Golden-winged_Woodpecker.jpg"
    "38_Kentucky_Warbler.jpg"
    "39_Crested_Titmouse.jpg"
    "40_American_Redstart.jpg"
    "41_Ruffed_Grouse.jpg"
    "42_Orchard_Oriole.jpg"
    "43_Cedar_Bird.jpg"
    "44_Summer_Red_Bird.jpg"
    "45_Traill's_Flycatcher.jpg"
    "46_Barred_Owl.jpg"
    "47_Ruby-throated_Humming_Bird.jpg"
    "48_Azure_Warbler.jpg"
    "49_Blue-green_Warbler.jpg"
    "50_Black_&_Yellow_Warbler.jpg"
    "51_Red-tailed_Hawk.jpg"
    "52_Chuck-will's_Widow.jpg"
    "53_Painted_Finch.jpg"
    "54_Rice_Bird.jpg"
    "55_Cuvier's_Regulus.jpg"
    "56_Red-shouldered_Hawk.jpg"
    "57_Loggerhead_Shrike.jpg"
    "58_Hermit_Thrush.jpg"
    "59_Chestnut-sided_Warbler.jpg"
    "60_Carbonated_Warbler.jpg"
    "61_Great_Horned_Owl.jpg"
    "62_Passenger_Pigeon.jpg"
    "63_White-eyed_Flycatcher_or_Vireo.jpg"
    "64_Swamp_Sparrow.jpg"
    "65_Rathbone_Warbler.jpg"
    "66_Ivory-billed_Woodpecker.jpg"
    "67_Red-winged_Starling_or_Marsh_Blackbird.jpg"
    "68_Republican_or_Cliff_Swallow.jpg"
    "69_Bay-breasted_Warbler.jpg"
    "70_Henslow's_Bunting.jpg"
    "71_Winter_Hawk.jpg"
    "72_Swallow-tailed_Hawk.jpg"
    "73_Wood_Thrush.jpg"
    "74_Indigo_Bird.jpg"
    "75_Le_Petit_Caporal.jpg"
    "76_Virginian_Partridge.jpg"
    "77_Belted_Kingfisher.jpg"
    "78_Great_Carolina_Wren.jpg"
    "79_Tyrant_Fly-catcher.jpg"
    "80_Prairie_Titlark.jpg"
    "81_Fish_Hawk_or_Osprey.jpg"
    "82_Whip-poor-will.jpg"
    "83_House_Wren.jpg"
    "84_Blue-Grey_Fly-catcher.jpg"
    "85_Yellow_Throated_Warbler.jpg"
    "86_Black_Warrior.jpg"
    "87_Florida_Jay.jpg"
    "88_Autumnal_Warbler.jpg"
    "89_Nashville_Warbler.jpg"
    "90_Black_&_White_Creeper.jpg"
    "91_Broad-winged_Hawk.jpg"
    "92_Pigeon_Hawk.jpg"
    "93_Sea-side_Finch.jpg"
    "94_Grass_Finch_or_Bay-winged_Bunting.jpg"
    "95_Yellow-poll_Warbler.jpg"
    "96_Columbia_Jay.jpg"
    "97_Little_Screech_Owl.jpg"
    "98_White-bellied_Swallow.jpg"
    "99_Cow-pen_Bird.jpg"
    "100_Marsh_Wren.jpg"
    "101_Raven.jpg"
    "102_Blue_Jay.jpg"
    "103_Canada_Warbler.jpg"
    "104_Chipping_Sparrow.jpg"
    "105_Red-breasted_Nuthatch.jpg"
    "106_Black_Vulture_or_Carrion_Crow.jpg"
    "107_Canada_Jay.jpg"
    "108_Fox-coloured_Sparrow.jpg"
    "109_Savannah_Finch.jpg"
    "110_Hooded_Warbler.jpg"
    "111_Pileated_Woodpecker.jpg"
    "112_Downy_Woodpecker.jpg"
    "113_Blue-bird.jpg"
    "114_White-crowned_Sparrow.jpg"
    "115_Wood_Pewee.jpg"
    "116_Ferruginous_Thrush.jpg"
    "117_Mississippi_Kite.jpg"
    "118_Warbling_Flycatcher.jpg"
    "119_Yellow-throated_Vireo.jpg"
    "120_Pewit_Flycatcher.jpg"
    "121_Snowy_Owl.jpg"
    "122_Blue_Grosbeak.jpg"
    "123_Black_&_Yellow_Warblers.jpg"
    "124_Green_Black-capt_Flycatcher.jpg"
    "125_Brown-headed_Nuthatch.jpg"
    "126_White-headed_Eagle.jpg"
    "127_Rose-breasted_Grosbeak.jpg"
    "128_Cat_Bird.jpg"
    "129_Great_Crested_Flycatcher.jpg"
    "130_Yellow-winged_Sparrow.jpg"
    "131_American_Robin.jpg"
    "132_Three-toed_Woodpecker.jpg"
    "133_Black-poll_Warbler.jpg"
    "134_Hemlock_Warbler.jpg"
    "135_Blackburnian_Warbler.jpg"
    "136_Meadow_Lark.jpg"
    "137_Yellow-breasted_Chat.jpg"
    "138_Connecticut_Warbler.jpg"
    "139_Field_Sparrow.jpg"
    "140_Pine_Creeping_Warbler.jpg"
    "141_I._Goshawk_-_2._Stanley_Hawk.jpg"
    "142_American_Sparrow_Hawk.jpg"
    "143_Golden-crowned_Thrush.jpg"
    "144_Small_Green_Crested_Flycatcher.jpg"
    "145_Yellow_Red-poll_Warbler.jpg"
    "146_Fish_Crow.jpg"
    "147_Night_Hawk.jpg"
    "148_Pine_Swamp_Warbler.jpg"
    "149_Sharp-tailed_Finch.jpg"
    "150_Red-eyed_Vireo.jpg"
    "151_Turkey_Buzzard.jpg"
    "152_White-breasted_Black-capped_Nuthatch.jpg"
    "153_Yellow-crown_Warbler.jpg"
    "154_Tennessee_Warbler.jpg"
    "155_Black-throated_Blue_Warbler.jpg"
    "156_American_Crow.jpg"
    "157_Rusty_Grakle.jpg"
    "158_American_Swift.jpg"
    "159_Cardinal_Grosbeak.jpg"
    "160_Black-capped_Titmouse.jpg"
    "161_Brasilian_Caracara_Eagle.jpg"
    "162_Zenaida_Dove.jpg"
    "163_Palm_Warbler.jpg"
    "164_Tawny_Thrush.jpg"
    "165_Bachmans_Finch.jpg"
    "166_Rough-legged_Falcon.jpg"
    "167_Key-west_Dove.jpg"
    "168_Fork-tailed_Flycatcher.jpg"
    "169_Mangrove_Cuckoo.jpg"
    "170_Gray_Tyrant.jpg"
    "171_Barn_Owl.jpg"
    "172_Blue-headed_Pigeon.jpg"
    "173_Barn_Swallow.jpg"
    "174_Olive_sided_Flycatcher.jpg"
    "175_Nuttall's_lesser-marsh_Wren.jpg"
    "176_Spotted_Grous.jpg"
    "177_White-crowned_Pigeon.jpg"
    "178_Orange-crowned_Warbler.jpg"
    "179_Wood_Wren.jpg"
    "180_Pine_Finch.jpg"
    "181_Goldon_Eagle.jpg"
    "182_Ground_Dove.jpg"
    "183_Goldon-crested-Wren.jpg"
    "184_Mangrove_Humming_Bird.jpg"
    "185_Bachman's_Warbler.jpg"
    "186_Pinnated_Grous.jpg"
    "187_Boat-tailed_Grackle.jpg"
    "188_Tree_Sparrow.jpg"
    "189_Snow_Bunting.jpg"
    "190_Yellow_bellied_Woodpecker.jpg"
    "191_Willow_Grous_or_Large_Ptarmigan.jpg"
    "192_Great_American_Shrike_or_Butcher_Bird.jpg"
    "193_Lincoln_Finch.jpg"
    "194_Canadian_Titmouse.jpg"
    "195_Ruby_crowned_Wren.jpg"
    "196_Labrador_Falcon.jpg"
    "197_American_Crossbill.jpg"
    "198_Brown_headed_Worm_eating_Warbler.jpg"
    "199_Little_Owl.jpg"
    "200_Shore_Lark.jpg"
    "201_Canada_Goose.jpg"
    "202_Red-Throated_Diver.jpg"
    "203_Fresh_Water_Marsh_Hen.jpg"
    "204_Salt_Water_Marsh_Hen.jpg"
    "205_Virginia_Rail.jpg"
    "206_Summer_or_Wood_Duck.jpg"
    "207_Booby_Gannet.jpg"
    "208_Esquimaux_Curlew.jpg"
    "209_Wilson's_Plover.jpg"
    "210_Least_Bittern.jpg"
    "211_Great_blue_Heron.jpg"
    "212_Common_Gull.jpg"
    "213_Puffin.jpg"
    "214_Razor_Bill.jpg"
    "215_Hyperborean_phalarope.jpg"
    "216_Wood_Ibiss.jpg"
    "217_Louisiana_Heron.jpg"
    "218_Foolish_Guillemot.jpg"
    "219_Black_Guillemot.jpg"
    "220_Piping_Plover.jpg"
    "221_Mallard_Duck.jpg"
    "222_White_Ibis.jpg"
    "223_Pied_oyster-catcher.jpg"
    "224_Kittiwake_Gull.jpg"
    "225_Kildeer_Plover.jpg"
    "226_Hooping_Crane.jpg"
    "227_Pin_tailed_Duck.jpg"
    "228_American_Green_winged_Teal.jpg"
    "229_Scaup_Duck.jpg"
    "230_Ruddy_Plover.jpg"
    "231_Long-billed_Curlew.jpg"
    "232_Hooded_Merganser.jpg"
    "233_Sora_or_Rail.jpg"
    "234_Tufted_Duck.jpg"
    "235_Sooty_Tern.jpg"
    "236_Night_Heron_or_Qua_bird.jpg"
    "237_Great_Esquimaux_Curlew.jpg"
    "238_Great_Marbled_Godwit.jpg"
    "239_American_Coot.jpg"
    "240_Roseate_Tern.jpg"
    "241_Black_Backed_Gull.jpg"
    "242_Snowy_Heron_or_White_Egret.jpg"
    "243_American_Snipe.jpg"
    "244_Common_Gallinule.jpg"
    "245_Thick-billed_Murre.jpg"
    "246_Eider_Duck.jpg"
    "247_Velvet_Duck.jpg"
    "248_American_Pied-bill_Dobchick.jpg"
    "249_Tufted_Auk.jpg"
    "250_Arctic_Tern.jpg"
    "251_Brown_Pelican.jpg"
    "252_Florida_Cormorant.jpg"
    "253_Jager.jpg"
    "254_Wilson's_Phalarope.jpg"
    "255_Red_Phalarope.jpg"
    "256_Purple_Heron.jpg"
    "257_Double-crested_Cormorant.jpg"
    "258_Hudsonian_Godwit.jpg"
    "259_Horned_Grebe.jpg"
    "260_Fork-tail_Petrel.jpg"
    "261_Hooping_Crane.jpg"
    "262_Tropic_Bird.jpg"
    "263_Pigmy_Curlew.jpg"
    "264_Fulmar_Petrel.jpg"
    "265_Buff_breasted_Sandpiper.jpg"
    "266_Common_Cormorant.jpg"
    "267_Arctic_Yager.jpg"
    "268_American_Woodcock.jpg"
    "269_Greenshank.jpg"
    "270_Stormy_Petrel.jpg"
    "271_Frigate_Pelican.jpg"
    "272_Richardson's_Jager.jpg"
    "273_Cayenne_Tern.jpg"
    "274_Semipalmated_Snipe,_or_Willet.jpg"
    "275_Noddy_Tern.jpg"
    "276_King_Duck.jpg"
    "277_Hutchins's_Barnacle_Goose.jpg"
    "278_Schinz's_Sandpiper_restored.jpg"
    "279_Cabot's_Tern.jpg"
    "280_Black_Tern.jpg"
    "281_Great_White_Heron.jpg"
    "282_White-winged_silvery_Gull.jpg"
    "283_Wandering_Shearwater.jpg"
    "284_Purple_Sandpiper.jpg"
    "285_Fork-tailed_Gull.jpg"
    "286_White-fronted_Goose.jpg"
    "287_Ivory_Gull.jpg"
    "288_Yellow_Shank.jpg"
    "289_Solitary_Sandpiper.jpg"
    "290_Red_backed_Sandpiper.jpg"
    "291_Herring_Gull.jpg"
    "292_Crested_Grebe.jpg"
    "293_Large_billed_Puffin.jpg"
    "294_Pectoral_Sandpiper.jpg"
    "295_Manks_Shearwater.jpg"
    "296_Barnacle_Goose.jpg"
    "297_Harlequin_Duck.jpg"
    "298_Red-necked_Grebe.jpg"
    "299_Dusky_Petrel.jpg"
    "300_Golden_Plover.jpg"
    "301_Canvas_backed_Duck.jpg"
    "302_Dusky_Duck.jpg"
    "303_Bartram_Sandpiper.jpg"
    "304_Turn-stone.jpg"
    "305_Purple_Gallinule.jpg"
    "306_Great_Northern_Diver_or_Loon.jpg"
    "307_Blue_Crane_or_Heron.jpg"
    "308_Tell-tale_Godwit_or_Snipe.jpg"
    "309_Great_Tern.jpg"
    "310_Spotted_Sandpiper.jpg"
    "311_American_White_Pelican.jpg"
    "312_Long-tailed_Duck.jpg"
    "313_Blue-Winged_Teal.jpg"
    "314_Black-headed_Gull.jpg"
    "315_Red-breasted_Sandpiper.jpg"
    "316_Black-bellied_Darter.jpg"
    "317_Black,_or_Surf_Duck.jpg"
    "318_American_Avocet.jpg"
    "319_Lesser_Tern.jpg"
    "320_Little_Sandpiper.jpg"
    "321_Roseate_Spoonbill.jpg"
    "322_Red-headed_Duck.jpg"
    "323_Black_Skimmer_or_Shearwater.jpg"
    "324_Bonapartian_Gull.jpg"
    "325_Buffel-headed_Duck.jpg"
    "326_Gannet.jpg"
    "327_Shoveller_Duck.jpg"
    "328_Long-legged_Avocet.jpg"
    "329_Yellow-breasted_Rail.jpg"
    "330_Ring_Plover.jpg"
    "331_Goosander.jpg"
    "332_Pied_Duck.jpg"
    "333_Green_Heron.jpg"
    "334_Black-bellied_Plover.jpg"
    "335_Red-breasted_Snipe.jpg"
    "336_Yellow-Crowned_Heron.jpg"
    "337_American_Bittern.jpg"
    "338_Bemaculated_Duck.jpg"
    "339_Little_Auk.jpg"
    "340_Least_Stormy-Petrel.jpg"
    "341_Great_Auk.jpg"
    "342_Golden-Eye_Duck.jpg"
    "343_Ruddy_Duck.jpg"
    "344_Long-legged_Sandpiper.jpg"
    "345_American_Widgeon.jpg"
    "346_Black-Throated_Diver.jpg"
    "347_Smew_or_White_Nun.jpg"
    "348_Gadwall_Duck.jpg"
    "349_Least_Water-hen.jpg"
    "350_Rocky_Mountain_Plover.jpg"
    "351_Great_Cinereous_Owl.jpg"
    "352_Black-Winged_Hawk.jpg"
    "353_I._Chesnut-backed_Titmouse_-_2._Black-capt_Titmouse_-_3._Chesnut-crowned_Titmouse.jpg"
    "354_I._Louisiana_Tanager_-_2._Scarlet_Tanager.jpg"
    "355_MacGillivray's_Finch.jpg"
    "356_Marsh_Hawk.jpg"
    "357_American_Magpie.jpg"
    "358_Pine_Grosbeak.jpg"
    "359_I._Arkansaw_Flycatcher_-_2._Swallow-Tailed_Flycatcher_-_3._Says_Flycatcher.jpg"
    "360_I._Winter_Wren_-_2._Rock_Wren.jpg"
    "361_Long-tailed_or_Dusky_Grous.jpg"
    "362_I._Yellow_billed_Magpie_-_2._Stellers_Jay_-_3._Ultramarine_Jay_-_4._Clark's_Crow.jpg"
    "363_Bohemian_Chatterer.jpg"
    "364_White-winged_Crossbill.jpg"
    "365_Lapland_Long-spur.jpg"
    "366_Iceland_or_Jer_Falcon.jpg"
    "367_Band-tailed_Pigeon.jpg"
    "368_Rock_Grous.jpg"
    "369_I._Mountain_Mocking_bird_-_2._Varied_Thrush.jpg"
    "370_American_Water_Ouzel.jpg"
    "371_Cock_of_the_Plains.jpg"
    "372_Common_Buzzard.jpg"
    "373_I._Evening_Grosbeak_-_2._Spotted_Grosbeak.jpg"
    "374_Sharp-shinned_Hawk.jpg"
    "375_Lesser_Red-Poll.jpg"
    "376_Trumpeter_Swan.jpg"
    "377_Scolopaceus_Courlan.jpg"
    "378_Hawk_Owl.jpg"
    "379_Ruff-necked_Humming-bird.jpg"
    "380_Tengmalm's_Owl.jpg"
    "381_Snow_Goose.jpg"
    "382_Sharp-tailed_Grous.jpg"
    "383_Long-eared_Owl.jpg"
    "384_Black-Throated_Bunting.jpg"
    "385_I._Bank_Swallow_-_2._Violet-green_Swallow.jpg"
    "386_White_Heron.jpg"
    "387_Glossy_Ibis.jpg"
    "388_I._Nuttall's_Starling_-_2._Yellow-headed_Troopial_-_3._Bullock's_Oriole.jpg"
    "389_Red-Cockaded_Woodpecker.jpg"
    "390_I._Lark_Finch_-_2._Prairie_Finch_-_3._Brown_Song_Sparrow.jpg"
    "391_Brant_Goose.jpg"
    "392_Louisiana_Hawk.jpg"
    "393_I._Townsend's_Warbler_-_2._Arctic_Blue-bird_-_3._Western_Blue-bird.jpg"
    "394_I._Chestnut-coloured_Finch_-_2._Black-headed_Siskin_-_3._Black_crown_Bunting_-_4._Arctic_Ground_Finch.jpg"
    "395_I._Audubon's_Warbler_-_2._Hermit_Warbler_-_3._Black-throated_gray_Warbler.jpg"
    "396_Burgomaster_Gull.jpg"
    "397_Scarlet_Ibis.jpg"
    "398_I._Lazuli_Finch_-_2._Clay-coloured_Finch_-_3._Oregon_Snow_Finch.jpg"
    "399_I._Black-throated_green_Warbler_-_2._Blackburnian_-_3._Mourning_Warbler.jpg"
    "400_I._Arkansaw_Siskin_-_2._Mealy_Red-poll_-_3._Louisiana_Tanager_-_4.Townsend's_Finch_-_5._Buff-breasted_Finch.jpg"
    "401_Red-breasted_Merganser.jpg"
    "402_I._Black-throated_Guillemot_-_2._Nobbed-billed_Auk_-_3._Curled-crested_Auk_-_4._Horned-billed_Guillemot.jpg"
    "403_Golden-eye_Duck.jpg"
    "404_Eared_Grebe.jpg"
    "405_Semipalmated_Sandpiper.jpg"
    "406_Trumpeter_Swan.jpg"
    "407_Dusky_Albatros.jpg"
    "408_American_Scoter_Duck.jpg"
    "409_I._Havell's_Tern_-_2._Trudeau's_Tern.jpg"
    "410_Marsh_Tern.jpg"
    "411_Common_American_Swan.jpg"
    "412_I._Violet-green_Cormorant_-_2._Townsend's_Cormorant.jpg"
    "413_California_Partridge.jpg"
    "414_I._Golden-winged_Warbler_-_2._Cape_May_Warbler.jpg"
    "415_I._Brown_Creeper_-_2._Californian_Nuthatch.jpg"
    "416_I._Hairy_Woodpecker_-_2._Red-bellied_Woodpecker_-_3._Red-shafted_Woodpecker_-_4._Lewis'_Woodpecker_-_5._Red-breasted_Woodpecker.jpg"
    "417_I._Maria's_Woodpecker_-_2._Three-toed_Woodpecker_-_3._Phillips'_Woodpecker_-_4._Canadian_Woodpecker_-_5._Harris's_Woodpecker_-_6._Audubon's_Woodpecker.jpg"
    "418_I._American_Ptarmigan_-_2._White-tailed_Grous.jpg"
    "419_I._Little_Tawny_Thrush_-_2._Ptiliogony's_Townsendi_-_3._Canada_Jay.jpg"
    "420_Prairie_Starling.jpg"
    "421_Brown_Pelican.jpg"
    "422_Rough-legged_Falcon.jpg"
    "423_I._Plumed--Partridge_-_2._Thick--legged_Partridge.jpg"
    "424_I._Lazuli_Finch_-_2._Crimson-necked_Bull-Finch_-_3._Gray-crowned_Linnet_-_4._Cow-pen_Bird_-_5._Evening_Grosbeak_-_6._Brown_Longspur.jpg"
    "425_Columbian_Humming_Bird.jpg"
    "426_Californian_Vulture.jpg"
    "427_I._White-legged_Oyster-catcher_-_2._Slender-billed_Oyster-catcher.jpg"
    "428_Townsend's_Sandpiper.jpg"
    "429_Western_Duck.jpg"
    "430_Slender-billed_Guillemot.jpg"
    "431_American_Flamingo.jpg"
    "432_I._Burrowing_Owl_-_2._Large-headed_Burrowing_Owl_-_3._Little_night_Owl_-_4._Columbian_Owl_-_5._Short-eared_Owl.jpg"
    "433_I._Bullock's_Oriole_-_2._Baltimore_Oriole_-_3._Mexican_Goldfinch_-_4._Varied_Thrush_-_5._Common_Water_Thrush.jpg"
    "434_I._Little_Tyrant_Fly-catcher_-_2._Small-headed_Fly-catcher_-_3._Blue_Mountain_Warbler_-_4._Bartran's_Vireo_-_5._Short-legged_Pewee_-_6._Rocky_Mountain_Fly-catcher.jpg"
    "435_I._Columbian_Water_Ouzel_-_2._Arctic_Water_Ouzel.jpg"
)

# Stats
total=${#images[@]}
success=0
failed=0
skipped=0
failed_files=()

echo "========================================="
echo "Audubon's Birds of America Downloader"
echo "========================================="
echo "Output directory: $OUTPUT_DIR"
echo "Total images: $total"
echo "Delay between downloads: ${DELAY}s"
echo ""

# Main download loop
for i in "${!images[@]}"; do
    filename="${images[$i]}"
    output_path="$OUTPUT_DIR/$filename"
    index=$((i + 1))
    
    # Skip if already exists
    if [ -f "$output_path" ]; then
        echo -e "[$index/$total] ${YELLOW}Skipping${NC} $filename (already exists)"
        skipped=$((skipped + 1))
        continue
    fi
    
    # Get direct URL
    url=$(get_direct_url "$filename")
    
    echo -e "[$index/$total] Downloading $filename..."
    
    if download_file "$filename" "$url"; then
        success=$((success + 1))
        echo -e "[$index/$total] ${GREEN}✓${NC} $filename"
    else
        failed=$((failed + 1))
        failed_files+=("$filename")
        echo -e "[$index/$total] ${RED}✗ Failed${NC} $filename"
    fi
    
    # Delay between downloads (but not after the last one)
    if [ $index -lt $total ]; then
        sleep $DELAY
    fi
done

# Summary
echo ""
echo "========================================="
echo "Download Complete"
echo "========================================="
echo -e "${GREEN}Successful:${NC} $success"
echo -e "${RED}Failed:${NC} $failed"
echo -e "${YELLOW}Skipped:${NC} $skipped"
echo "Total: $total"

if [ ${#failed_files[@]} -gt 0 ]; then
    echo ""
    echo "Failed files:"
    for file in "${failed_files[@]}"; do
        echo "  - $file"
    done
fi